- name: Wipe application
  block:
    - name: Stop and remove containers
      community.docker.docker_compose_v2:
        project_src: "{{ deploy_directory }}"
        state: absent
      when: web_app_full_wipe | bool
      ignore_errors: yes

    - name: Remove application directory
      file:
        path: "{{ deploy_directory }}"
        state: absent
      when: web_app_full_wipe | bool
      ignore_errors: yes

    - name: Remove Docker image
      community.docker.docker_image:
        name: "{{ app_image }}"
        state: absent
        force_absent: true
      when: web_app_full_wipe | bool
  tags:
    - wipe 